// Scoring — DESIGN.md §9.
// score(key) = round( sum(answers where question.key === key) / 7 , 1 )
// Each intelligence has exactly 7 questions, so dividing by 7 yields 1.0–5.0.
// The Student ID is generated by the backend at `submit` time (§9, §10) —
// no client-side ID logic lives here.

import { QUESTIONS, type IntelligenceKey } from "./questions";
import { INTELLIGENCE_ORDER, INTELLIGENCES } from "./intelligences";

export type Scores = Record<IntelligenceKey, number>;

/** Round to one decimal place. */
function round1(n: number): number {
  return Math.round(n * 10) / 10;
}

/**
 * Compute the 8 scores from a 56-element answers array (1..5 each, indexed by
 * question number minus 1). Returns one decimal per key, 1.0–5.0.
 */
export function computeScores(answers: readonly number[]): Scores {
  const sums: Record<IntelligenceKey, number> = {
    word_smart: 0, logic_smart: 0, music_smart: 0, picture_smart: 0,
    body_smart: 0, people_smart: 0, self_smart: 0, nature_smart: 0,
  };
  const counts: Record<IntelligenceKey, number> = {
    word_smart: 0, logic_smart: 0, music_smart: 0, picture_smart: 0,
    body_smart: 0, people_smart: 0, self_smart: 0, nature_smart: 0,
  };

  for (const q of QUESTIONS) {
    const a = answers[q.n - 1];
    if (typeof a === "number") {
      sums[q.key] += a;
      counts[q.key] += 1;
    }
  }

  const out = {} as Scores;
  for (const k of INTELLIGENCE_ORDER) {
    out[k] = counts[k] > 0 ? round1(sums[k] / counts[k]) : 0;
  }
  return out;
}

/**
 * Top intelligence by score. Ties resolved by §4 order
 * (Word → Logic → Music → Picture → Body → People → Self → Nature).
 */
export function topIntelligence(scores: Scores): IntelligenceKey {
  let bestKey: IntelligenceKey = INTELLIGENCE_ORDER[0];
  let bestScore = -Infinity;
  for (const k of INTELLIGENCE_ORDER) {
    if (scores[k] > bestScore) {
      bestScore = scores[k];
      bestKey = k;
    }
  }
  return bestKey;
}

/** Friendly label for the top intelligence ("Music Smart" etc.). */
export function topIntelligenceLabel(scores: Scores): string {
  return INTELLIGENCES[topIntelligence(scores)].label;
}
